# Simple workflow for deploying static content to GitHub Pages
name: Deploy Shadcn Admin Kit

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    env:
      VITE_CHATWOOT_URL: ${{ vars.VITE_CHATWOOT_URL }}
      VITE_CHATWOOT_WEBSITE_TOKEN: ${{ secrets.VITE_CHATWOOT_WEBSITE_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build components
        run: make build

      - name: Deploy to gh-pages branch
        run: |
          # Save the built public folder
          mkdir -p /tmp/new_public
          cp -r public/* /tmp/new_public/

          # Switch to gh-pages branch
          git stash
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin gh-pages
          git checkout gh-pages

          # Update gh-pages folder with new public folder content preserving releases
          rsync -a --delete --exclude='.git/' --exclude='r/*/' /tmp/new_public/ ./

          # Commit and push
          git add -A
          git commit -m "Deploy: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes"
          git push origin gh-pages
