#!/usr/bin/env python3
"""Build a shadow evidence bundle from dry-run, mirror, and gate check outputs.

Nothing in this tool connects to a live gateway or requires a staging environment.
Missing inputs produce warnings (default) or errors (strict), never a fatal crash.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

# Re-use helpers from sibling check tools
import check_shadow_evidence  # noqa: E402
import check_cutover_readiness  # noqa: E402
import check_observability_contract  # noqa: E402


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build shadow evidence bundle.")
    parser.add_argument("--shadow-report", default=None, help="path to reports/shadow/latest.json")
    parser.add_argument("--mirror-report", default=None, help="path to reports/shadow/mirror-latest.json")
    parser.add_argument("--out", type=Path, default=None, help="output directory (default: reports/shadow/bundles/<timestamp>)")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--strict", action="store_true", help="fail if live evidence is missing")
    parser.add_argument("--git-commit", default=None, help="git commit SHA (auto-detected if omitted)")
    parser.add_argument("--staging-report", default=None, help="path to reports/staging/percentage-canary-1pct-latest.json")
    return parser.parse_args(argv)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def detect_git_commit(root: Path) -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True, text=True, timeout=5, cwd=root,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return "unknown"


def timestamp_now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def safe_load_json(path: Path) -> dict[str, Any] | None:
    try:
        return check_shadow_evidence.load_json(path)
    except (ValueError, Exception):
        return None


def safe_load_json_yaml(path: Path) -> dict[str, Any] | None:
    try:
        return check_cutover_readiness.load_json_yaml(path)
    except (ValueError, Exception):
        return None


def safe_run_check(tool_module, *args) -> dict[str, Any]:
    """Run a check tool function and capture structured output."""
    try:
        errors = tool_module(*args)
        return {"ok": len(errors) == 0, "errors": errors}
    except Exception as exc:
        return {"ok": False, "errors": [str(exc)]}


# ---------------------------------------------------------------------------
# Bundle builders
# ---------------------------------------------------------------------------

def build_manifest(args: argparse.Namespace, bundle_dir: Path) -> dict[str, Any]:
    root = args.root
    report_dir = root / "reports" / "shadow"
    shadow_path = Path(args.shadow_report) if args.shadow_report else report_dir / "latest.json"
    mirror_path = Path(args.mirror_report) if args.mirror_report else report_dir / "mirror-latest.json"
    if args.staging_report:
        staging_path = Path(args.staging_report)
    else:
        staging_path = root / "reports" / "staging" / "header-canary-latest.json"
    commit = args.git_commit or detect_git_commit(root)

    shadow = safe_load_json(shadow_path)
    mirror = safe_load_json(mirror_path)
    staging = safe_load_json(staging_path)

    # Route inventory (generated by check_route_contract.py --inventory)
    route_inventory_path = bundle_dir / "route-inventory.txt"
    try:
        subprocess.run(
            [sys.executable, str(root / "tools" / "check_route_contract.py"), "--root", str(root), "--inventory"],
            capture_output=True, timeout=30,
        )
    except Exception:
        pass

    # Cutover readiness
    policy_path = root / "configs" / "cutover_policy.yaml"
    routes_path = root / "contracts" / "routes.yaml"
    cutover_ok = True
    if policy_path.is_file() and routes_path.is_file():
        policy = safe_load_json_yaml(policy_path)
        routes = safe_load_json_yaml(routes_path)
        if policy and routes:
            errors = []
            errors.extend(check_cutover_readiness.validate_policy_shape(policy))
            errors.extend(check_cutover_readiness.validate_allowed_routes(policy, routes))
            errors.extend(check_cutover_readiness.validate_blocked_routes(policy))
            errors.extend(check_cutover_readiness.validate_blocked_vs_allowed(policy))
            errors.extend(check_cutover_readiness.validate_rollback_triggers(policy))
            cutover_ok = len(errors) == 0

    # Observability contract
    obs_contract_path = root / "configs" / "observability_contract.yaml"
    obs_fixtures_dir = root / "tests" / "fixtures" / "observability"
    obs_ok = True
    if obs_contract_path.is_file():
        contract = safe_load_json_yaml(obs_contract_path)
        if contract:
            errors = check_observability_contract.validate_contract_shape(contract)
            errors.extend(check_observability_contract.check_fixtures(obs_fixtures_dir, contract))
            obs_ok = len(errors) == 0

    # Validate staging header-canary report if available
    staging = safe_load_json(staging_path)

    # Summary fields
    summary: dict[str, Any] = {
        "health_ok": shadow.get("summary", {}).get("health_ok") if shadow else None,
        "route_count": shadow.get("summary", {}).get("route_count") if shadow else None,
        "legacy_gaps": shadow.get("summary", {}).get("legacy_gaps") if shadow else None,
        "deprecated_aliases": shadow.get("summary", {}).get("deprecated_aliases") if shadow else None,
        "chat_parity": shadow.get("summary", {}).get("chat_parity") if shadow else None,
        "admin_post_parity": shadow.get("summary", {}).get("admin_post_parity") if shadow else None,
        "mirror_result": mirror.get("summary", {}).get("executed_cases") if mirror else None,
        "unexpected_diffs": shadow.get("summary", {}).get("unexpected_diffs") if shadow else None,
        "latency_warn_count": (shadow or {}).get("latency", {}).get("chat_warn_count"),
        "strict_ready": False,
    }

    # Staging evidence (after summary is defined)
    if staging is not None:
        summary["staging_header_canary"] = staging.get("status", "unknown")
        if staging.get("status") in ("completed", "passed"):
            summary["staging_evidence_ok"] = True
        elif staging.get("status") == "skipped" or staging.get("status") == "skipped_live_check":
            summary["staging_evidence_ok"] = None  # Unknown without staging env
    else:
        summary["staging_header_canary"] = None
        summary["staging_evidence_ok"] = False

    if args.strict:
        strict_conditions = [
            shadow and shadow.get("summary", {}).get("chat_parity") == "passed",
            shadow and shadow.get("summary", {}).get("admin_post_parity") == "passed",
            mirror and mirror.get("mode") == "live",
            mirror and mirror.get("summary", {}).get("drifted_cases") == 0,
        ]
        summary["strict_ready"] = all(strict_conditions)
    else:
        summary["strict_ready"] = None  # unknown without strict evidence

    manifest = {
        "generated_at": timestamp_now(),
        "git_commit": commit,
        "bundle_version": 1,
        "mode": "local" if not args.strict else "staging_strict",
    "inputs": {
        "shadow_report": str(shadow_path),
        "mirror_report": str(mirror_path),
        "staging_report": str(staging_path),
        "route_inventory": "route-inventory.txt",
        "cutover_readiness": "cutover-readiness.json",
        "observability_contract": "observability-contract.json"
    },
        "privacy": {
            "raw_payload_included": False,
            "contains_pii": False,
            "redacted": True,
        },
        "summary": summary,
        "gates": {
            "cutover_readiness_ok": cutover_ok,
            "observability_contract_ok": obs_ok,
            "shadow_evidence_ok": shadow is not None,
            "mirror_evidence_ok": mirror is not None,
            "staging_evidence_ok": staging is not None and staging.get("status") in ("completed", "passed"),
        },
    }
    return manifest


def write_bundle_files(
    args: argparse.Namespace, bundle_dir: Path, manifest: dict[str, Any], staging_path: Path
) -> list[str]:
    """Copy or generate each bundle artifact. Returns warnings."""
    warnings: list[str] = []
    root = args.root
    report_dir = root / "reports" / "shadow"

    shadow_path = Path(args.shadow_report) if args.shadow_report else report_dir / "latest.json"
    mirror_path = Path(args.mirror_report) if args.mirror_report else report_dir / "mirror-latest.json"

    # 1. shadow-report.json
    if shadow_path.is_file():
        dest = bundle_dir / "shadow-report.json"
        dest.write_text(shadow_path.read_text(encoding="utf-8"), encoding="utf-8")
    else:
        warnings.append(f"shadow report not found: {shadow_path}")
        if args.strict:
            raise ValueError(f"strict mode requires shadow report: {shadow_path}")

    # 2. mirror-report.json
    if mirror_path.is_file():
        dest = bundle_dir / "mirror-report.json"
        dest.write_text(mirror_path.read_text(encoding="utf-8"), encoding="utf-8")
    else:
        warnings.append(f"mirror report not found: {mirror_path}")
        if args.strict:
            raise ValueError(f"strict mode requires mirror report: {mirror_path}")

    # 3. route-inventory.txt
    inventory_path = bundle_dir / "route-inventory.txt"
    try:
        result = subprocess.run(
            [sys.executable, str(root / "tools" / "check_route_contract.py"), "--root", str(root), "--inventory"],
            capture_output=True, text=True, timeout=30,
        )
        inventory_path.write_text(result.stdout + result.stderr, encoding="utf-8")
    except Exception as exc:
        warnings.append(f"route inventory generation failed: {exc}")

    # 4. cutover-readiness.json
    policy_path = root / "configs" / "cutover_policy.yaml"
    routes_path = root / "contracts" / "routes.yaml"
    if policy_path.is_file() and routes_path.is_file():
        policy = safe_load_json_yaml(policy_path)
        routes = safe_load_json_yaml(routes_path)
        if policy and routes:
            data = {
                "policy": policy,
                "routes_summary": {"count": len(routes.get("routes", []))},
                "validations": {
                    "policy_shape_ok": len(check_cutover_readiness.validate_policy_shape(policy)) == 0,
                    "allowed_routes_ok": len(check_cutover_readiness.validate_allowed_routes(policy, routes)) == 0,
                    "blocked_routes_ok": len(check_cutover_readiness.validate_blocked_routes(policy)) == 0,
                },
            }
            (bundle_dir / "cutover-readiness.json").write_text(
                json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8",
            )

    # 5. observability-contract.json
    obs_path = root / "configs" / "observability_contract.yaml"
    if obs_path.is_file():
        contract = safe_load_json_yaml(obs_path)
        if contract:
            (bundle_dir / "observability-contract.json").write_text(
                json.dumps(contract, indent=2, ensure_ascii=False), encoding="utf-8",
            )

    # 6. header-canary-report.json
    if staging_path.is_file():
        dest = bundle_dir / "header-canary-report.json"
        dest.write_text(staging_path.read_text(encoding="utf-8"), encoding="utf-8")
    else:
        warnings.append(f"staging header-canary report not found: {staging_path}")
        if args.strict:
            raise ValueError(f"strict mode requires staging report: {staging_path}")

    # 7. evidence-summary.md
    generate_evidence_summary(bundle_dir, manifest, root)

    return warnings


def generate_evidence_summary(bundle_dir: Path, manifest: dict[str, Any], root: Path) -> None:
    summary = manifest.get("summary", {})
    gates = manifest.get("gates", {})
    lines: list[str] = []
    lines.append("# Shadow Evidence Bundle")
    lines.append("")
    lines.append("## Summary")
    lines.append(f"- Mode: {manifest.get('mode', 'unknown')}")
    lines.append(f"- Generated at: {manifest.get('generated_at', 'unknown')}")
    lines.append(f"- Git commit: {manifest.get('git_commit', 'unknown')}")
    lines.append(f"- Route count: {summary.get('route_count', 'N/A')}")
    lines.append(f"- Legacy gaps: {summary.get('legacy_gaps', 'N/A')}")
    lines.append(f"- Deprecated aliases: {summary.get('deprecated_aliases', 'N/A')}")
    lines.append(f"- Chat parity: {summary.get('chat_parity', 'N/A')}")
    lines.append(f"- Admin POST parity: {summary.get('admin_post_parity', 'N/A')}")
    lines.append(f"- Mirror result: {summary.get('mirror_result', 'N/A')}")
    lines.append(f"- Unexpected diffs: {summary.get('unexpected_diffs', 'N/A')}")
    lines.append(f"- Latency warnings: {summary.get('latency_warn_count', 'N/A')}")
    lines.append(f"- Strict ready: {summary.get('strict_ready', 'N/A')}")
    lines.append("")

    lines.append("## Gates")
    for gate_name, gate_ok in gates.items():
        status = "PASS" if gate_ok else "FAIL"
        lines.append(f"- {gate_name}: {status}")
    lines.append("")

    lines.append("## Inputs")
    inputs = manifest.get("inputs", {})
    for key, value in inputs.items():
        lines.append(f"- {key}: {value}")
    lines.append("")

    lines.append("## Privacy")
    privacy = manifest.get("privacy", {})
    lines.append(f"- Raw request bodies included: {privacy.get('raw_payload_included', 'N/A')}")
    lines.append(f"- PII included: {privacy.get('contains_pii', 'N/A')}")
    lines.append(f"- Redacted: {privacy.get('redacted', 'N/A')}")
    lines.append("")

    lines.append("## Next Action")
    if all(gates.values()):
        lines.append("All gates pass. Safe to proceed with next phase.")
    else:
        lines.append("One or more gates failed. Review warnings before proceeding.")

    (bundle_dir / "evidence-summary.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    args = parse_args()
    root = args.root
    bundles_dir = root / "reports" / "shadow" / "bundles"
    bundles_dir.mkdir(parents=True, exist_ok=True)

    timestamp = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    bundle_dir = args.out if args.out else bundles_dir / timestamp
    bundle_dir.mkdir(parents=True, exist_ok=True)

    print(f"building evidence bundle: {bundle_dir}")

    manifest = build_manifest(args, bundle_dir)
    staging_path = manifest.get("inputs", {}).get("staging_report", "")
    if staging_path:
        staging_path = Path(staging_path)
    else:
        staging_path = Path("reports/staging/header-canary-latest.json")

    try:
        warnings = write_bundle_files(args, bundle_dir, manifest, staging_path)
    except ValueError as exc:
        print(f"BUNDLE FAIL: {exc}", file=sys.stderr)
        return 1

    # Write manifest last (so partial failures don't produce a misleading manifest)
    manifest_path = bundle_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    # Write bundle.json (top-level pointer)
    bundle_json = {
        "bundle_dir": str(bundle_dir),
        "manifest": json.loads(manifest_path.read_text(encoding="utf-8")),
    }
    (bundle_dir / "bundle.json").write_text(json.dumps(bundle_json, indent=2, ensure_ascii=False), encoding="utf-8")

    for warning in warnings:
        print(f"BUNDLE WARNING: {warning}", file=sys.stderr)

    print(f"bundle complete: {bundle_dir}")
    print(json.dumps(json.loads(manifest_path.read_text(encoding="utf-8")), indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
